### ISSUE TITLE
Interactive elements lose their values while being dragged

### ISSUE THREAD

**Issue by mmilo** [rodrigodagostino/svelte-sortable-list#11]
Thanks Rodrigo for the incredible work on this library, it’s the most thoughtfully sorting library I’ve come across thus far.

One small issue I’ve encountered is that interactive elements lose their values while being dragged. Below is a video of what I mean
![dragging](https://github.com/user-attachments/assets/abb7eddc-f117-4ab5-92a4-f9ab23a02661)

I had a look at React Movable which doesn’t have the same issue so I’m not sure if this is a Svelte specific quirk or something else
![dragging-2](https://github.com/user-attachments/assets/0daa2cc4-91db-4285-883a-9495ad3f261e)

In any case, keep up the great work and all the best for the upcoming Svelte 5 migration.

**Comment by rodrigodagostino** [comment]
Hey, @mmilo! Thank you for sharing your thoughts. It’s very fulfilling to see that my work has been useful to someone out there :)

And yes, that issue has been present since I added the dynamic elements feature into the library. I made a few attempts to solve it, but I was not able to find a solution, and since it wasn’t a critical bug, I decided to move on until I could find the time to work on it.

So thank you for the reminder :) I will keep the issue open until I can find a solution for this bug.

**Comment by rodrigodagostino** [comment]
Hi again, @mmilo! Just wanted to let you know that I’ve just published a new version fixing the bug we’ve been discussing about. Please, give it a go whenever you have the time and let me know how it went :)

**Comment by mmilo** [comment]
Amazing, yes this works great now! Thanks for getting to this so quickly, especially given it’s a holiday period. Hope you have a great new year!

**Comment by rodrigodagostino** [comment]
Thank you for your contribution, @mmilo! Have a happy new year! :)
